#!/usr/bin/env python

import sys
import CommandShell as cs


if __name__ == '__main__':
    args = cs.parse_command(sys.argv[1:])

    if args['--interactive']:
        cli = cs.CommandShell('Program')
        cli.cmdloop()
    else:
        cs.run_subcommand(args)
