#!/usr/bin/env python

import sys
import CommandShell as cs
import docopt


if __name__ == '__main__':
    args = cs.parse_command(sys.argv[1:])
    #args = docopt.docopt(__doc__, argv=sys.argv[1:], version='0.1.0')

    #if args['--version']:

    #if args['--interactive']:
    #    cli = cs.CommandShell('Program')
    #    cli.cmdloop()